/*
Copyright © 2023 IITS-Consulting

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
package cmd

import (
	"log"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

//nolint:gochecknoglobals // autogenerated and recommended by spf13/cobra
var documentationCmd = &cobra.Command{
	Use:   "documentation",
	Short: "Generates markdown documentation",
	RunE: func(cmd *cobra.Command, args []string) error {
		err := doc.GenMarkdownTree(cmd.Root(), "./generated-docs/")
		log.Println("documentation generated")
		return err
	},
}

//nolint:gochecknoinits // autogenerated and recommended by spf13/cobra
func init() {
	RootCmd.AddCommand(documentationCmd)
}
